In [ ]:
import numpy as np

# Part 2: Numerical Analysis with NumPy

### Array Creation and Indexing

##### Create a 1D NumPy array of integers from 1 to 20.

In [ ]:
a= np.array(np.arange(1,21))   # with the help of arange , array will get the number between 0 and 21
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


##### Extract the even numbers from this array using slicing.

In [ ]:
a= np.array(np.arange(2,21,2))
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


##### Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.

In [ ]:
c=np.random.randint(10,101 , size=(5,4))
print(c)

[[89 91 36 22]
 [18 18 92 12]
 [38 63 76 55]
 [68 66 27 92]
 [86 81 14 44]]


##### Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).

In [ ]:
d=c[1:4,1:3]
print(d)

[[18 92]
 [63 76]
 [66 27]]


### Array Manipulation

##### Reshape the 1D array of integers into a 4x5 2D array.

In [ ]:
a=np.array(np.arange(1,21))
print(a)

b=a.reshape(4,5)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


##### Flatten the 2D array back to a 1D array and print it.

In [ ]:
c=b.flatten()
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


##### Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).

In [ ]:
a=np.array(np.random.randint(1,10,size=(5,4)))
print(a)
b=np.array(np.random.randint(11,20, size=(4,5)))
print(b)
print(np.matmul(a,b))      #it is the product of matrix a and then b ie. a*b. 
                    # if we write np.matmul(b,a) it will give us the product as b*a

[[8 6 3 8]
 [1 6 5 5]
 [2 1 7 2]
 [2 9 8 2]
 [3 9 4 9]]
[[15 14 16 16 18]
 [18 19 18 13 19]
 [17 12 17 15 13]
 [18 18 12 14 11]]
[[423 406 383 363 385]
 [298 278 269 239 252]
 [203 167 193 178 168]
 [364 331 354 297 333]
 [437 423 386 351 376]]


### Boolean and Fancy Indexing

##### Create a NumPy array of 50 random integers between 0 and 100.

In [ ]:
a = np.random.randint(1,100, size=50)
print(a)

[86 39 45 44 41 25 99 32 21 56 20 38 32 69 88 21 58  4 97 18 40 52 54 30
 77 66  3 60 16 32 41  6 81 58 12 29 71 10  6 55 50 47 50 24 99 36  7 64
 74 97]


##### Use Boolean indexing to extract all values greater than 50 from the array

In [ ]:
b=np.array([a>50])
print(b)

[[ True False False False False False  True False False  True False False
  False  True  True False  True False  True False False  True  True False
   True  True False  True False False False False  True  True False False
   True False False  True False False False False  True False False  True
   True  True]]


##### Use fancy indexing to extract elements from the array at specific indices.

In [ ]:
b=np.random.randint(0,50, size=50)
c=a[b]
print(c)         #b is an random array whose elements lies between 0 and 50 , and c is an array whose elemnets point towards to a by the index 
                 #of the elements in b , which is also random

[54 47 58  6 47 29 64 99 74 58 24 66 29 16 44 32 55  3 88 97 41  6  7 88
 16 52 29  6 18 32 32 44 55 88 32 97 69 18 12 25 88 30 44  3 60 97 41  3
  6 12]


### Statistical Operations

##### For the 2D array created earlier, calculate the mean, max, and sum along each column

In [ ]:
a=np.array(np.random.randint(1,100, size=(10,5)))
mean = np.mean(a,axis=0)           #this array contain all the mean value along the column as axis is 0
maxm = np.max(a,axis=0 )            #this array contain maximum  value along the column as axis is 0
sumation = np.sum(a,axis=0)        #this array contain summation along the column as axis is 0
print(a)         
print(mean)
print(maxm)
print(sumation)

[[61 16 52 75  3]
 [69 96 12 92 88]
 [47 83 68 98 12]
 [79  1  1 60 53]
 [85 30 28 52 56]
 [20 96  8 16 31]
 [14 18 75 68 76]
 [51 17 39 94 80]
 [41 46 11 50 71]
 [69 70 74 90 40]]
[53.6 47.3 36.8 69.5 51. ]
[85 96 75 98 88]
[536 473 368 695 510]


##### Create a mask to select elements that are greater than the mean value for each column and apply the mask to filter the array.

In [ ]:
mask = a > mean
print(mask)
required = a[mask]
print(required)

[[ True False  True  True False]
 [ True  True False  True  True]
 [False  True  True  True False]
 [ True False False False  True]
 [ True False False False  True]
 [False  True False False False]
 [False False  True False  True]
 [False False  True  True  True]
 [False False False False  True]
 [ True  True  True  True False]]
[61 52 75 69 96 92 88 83 68 98 79 53 85 56 96 75 76 39 94 80 71 69 70 74
 90]


# Part 4: Bonus Challenge

### Advanced NumPy Manipulation

##### Create a 3D NumPy array with specific dimensions and populate it with random numbers

In [ ]:
a=np.array(np.random.randint(1,100, size=(4,5,6)))
print(a)

[[[28  3 89 25 21 88]
  [ 7 36 50 54 81  4]
  [16 94  9 89 85 26]
  [ 6 40 86 55 81 38]
  [30 75 86 38 99 42]]

 [[ 6 49 99 18 88 77]
  [10 48 41 79 37 59]
  [88 80 14 33 45 76]
  [63 71 20  3 36 31]
  [48 59 99 93 42 10]]

 [[87 74 38 74 87  4]
  [ 8 30 24  4 39 63]
  [40 38 66 74  7 22]
  [13 37 35 97 55 77]
  [28 28 88 45  2 36]]

 [[85 42 52 56 76 48]
  [72 85 43 32 42 39]
  [68 21 26 97 79 84]
  [84 99 87  5 77 69]
  [ 8 69 95 38 27 47]]]


##### Swap two of its axes.

In [ ]:
swap = np.swapaxes(a,0,1)      #here i have swaped axis 0 and 1 hence now its size is 5,4,6
print(swap)

[[[28  3 89 25 21 88]
  [ 6 49 99 18 88 77]
  [87 74 38 74 87  4]
  [85 42 52 56 76 48]]

 [[ 7 36 50 54 81  4]
  [10 48 41 79 37 59]
  [ 8 30 24  4 39 63]
  [72 85 43 32 42 39]]

 [[16 94  9 89 85 26]
  [88 80 14 33 45 76]
  [40 38 66 74  7 22]
  [68 21 26 97 79 84]]

 [[ 6 40 86 55 81 38]
  [63 71 20  3 36 31]
  [13 37 35 97 55 77]
  [84 99 87  5 77 69]]

 [[30 75 86 38 99 42]
  [48 59 99 93 42 10]
  [28 28 88 45  2 36]
  [ 8 69 95 38 27 47]]]


##### Perform an operation to calculate the sum of all the elements along a particular axis.

In [ ]:
sum_0 = np.sum(a,axis=0)       #calculate sum along the depth 
print(sum_0)

sum_1 = np.sum(a,axis=1)       #calculate sum along the column of each slice
print(sum_1)

sum_2 = np.sum(a,axis=2)       #calculate sum along row of each slice
print(sum_2)

[[206 168 278 173 272 217]
 [ 97 199 158 169 199 165]
 [212 233 115 293 216 208]
 [166 247 228 160 249 215]
 [114 231 368 214 170 135]]
[[ 87 248 320 261 367 198]
 [215 307 273 226 248 253]
 [176 207 251 294 190 202]
 [317 316 303 228 301 287]]
[[254 232 319 306 370]
 [337 274 336 224 351]
 [364 168 247 314 227]
 [359 313 375 421 284]]


##### Generate a random array and use broadcasting to perform an operation that adds a vector to each row of a 2D array.

In [ ]:
a_2d = np.array(np.random.randint(1,100, size=(10,5)))
print(a_2d)
print("    ")
a_1d = np.random.randint(1,100, size=5)
print(a_1d)
print("   ")
sum = a_2d + a_1d
print(sum)

[[38 90 25 71 65]
 [45 53 47 54 38]
 [59 53 46 50 49]
 [98 97 79  5 55]
 [62 52  7 30  6]
 [17 73 55  5 86]
 [69 76 77 59 37]
 [11 88 35 52 19]
 [49 21  6 62 67]
 [89 91 22 89 54]]
    
[34 65 84 99 14]
   
[[ 72 155 109 170  79]
 [ 79 118 131 153  52]
 [ 93 118 130 149  63]
 [132 162 163 104  69]
 [ 96 117  91 129  20]
 [ 51 138 139 104 100]
 [103 141 161 158  51]
 [ 45 153 119 151  33]
 [ 83  86  90 161  81]
 [123 156 106 188  68]]


# Part 3: Problem Solving with Python Basics

### Loops and Conditional Statements

##### Print the Fibonacci sequence up to 100 using a loop.


In [ ]:
i=1
a=1
b=1
print(a)
print(b)
c=a+b
while i<=98:
    print(c)
    a=b
    b=c
    c=a+b
    i=i+1


1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817
39088169
63245986
102334155
165580141
267914296
433494437
701408733
1134903170
1836311903
2971215073
4807526976
7778742049
12586269025
20365011074
32951280099
53316291173
86267571272
139583862445
225851433717
365435296162
591286729879
956722026041
1548008755920
2504730781961
4052739537881
6557470319842
10610209857723
17167680177565
27777890035288
44945570212853
72723460248141
117669030460994
190392490709135
308061521170129
498454011879264
806515533049393
1304969544928657
2111485077978050
3416454622906707
5527939700884757
8944394323791464
14472334024676221
23416728348467685
37889062373143906
61305790721611591
99194853094755497
160500643816367088
259695496911122585
420196140727489673
679891637638612258
1100087778366101931
1779979416004714189
2880067194370816120
4660046610375530309
7540113804746346429


##### Loop through the numbers from 1 to 50 and print:
"Fizz" for multiples of 3.
"Buzz" for multiples of 5.
"FizzBuzz" for multiples of both 3 and 5.

In [ ]:
for i in range(1,51):
    if i%15==0:
        print("FizzBuzz")
    elif i%3==0:
        print("Fizz")
    elif i%5==0:
        print("Buzz")
    else :
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


### Variable-Length Arguments

##### Write a solution that accepts a list of numbers and returns the median value.

In [ ]:
list = []
n=int(input("How many numbers do you want to enter:"))
i=0
while i<n:
    num =int(input("enter the number:"))
    list.append(num)
    i +=1
list.sort()
m= (list[n//2]+list[n//2 -1])/2

if n%2!=0:
    print("the required median of your data is:" + str(list[n // 2]))
else :
    print(f"the required median of your data is:{m}")


How many numbers do you want to enter: 2
enter the number: 1
enter the number: 2


the required median of your data is:1.5


##### Write a solution that accepts a variable number of arguments and returns the average of the numbers.

In [ ]:
list =[]
print("enter 'spacebar' if you have entered all your number" )
while True:
    a = input("enter the number:")
    if a==" ":
        break
    list.append(int(a))
n=len(list)
b=0
for i in range(0,n):
    b=b+list[i]
print(f'mean of the data provided by you is {b/n}')

enter 'spacebar' if you have entered all your number


enter the number: 1
enter the number:  


mean of the data provided by you is 1.0


### Error Handling

##### Handle the case where a division by zero occurs and print an appropriate error message.

In [ ]:
## we will creat an calculator using python only for division
a=int(input("Enter first numbere:"))
b=int(input("Enter second number:"))
if b!=0:
    print(f"a divide by b is {a/b}")
else :
    print("a divide by b is not defined")
if a!=0:
    print(f"b divide by a is {b / a}")
else:
    print("b divide by a is not defined")


Enter first numbere: 1
Enter second number: 2


a divide by b is 0.5
b divide by a is 2.0
